### PR TITLE
Automatically run tests on commit

### PR DESCRIPTION
**Pull request by odahcam**
**This requires Travis-CI:**

image

With that you get tests running automatically with every commit **for free**. It'll run the test server on the cloud and run test assertions to make sure everything is working.

[See it working](https://github.com/zxing-js/text-encoding/runs/657876220)!

### CODE REVIEW

**Comment by username1565** [comment]
Thanks for your changes. I did merge this changes, but I see by your link the following error:
```
 The build errored.
```
https://travis-ci.com/github/zxing-js/text-encoding/builds/164836384
```
 master Rename travis.yml to .travis.yml
```
```
1.1
 yarn test:serve

yarn run v1.15.2

error Command "test:serve" not found.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The command "yarn test:serve" failed and exited with 1 during .

Your build has been stopped.
```

```
1.2
$ yarn test:serve

yarn run v1.15.2

error Command "test:serve" not found.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The command "yarn test:serve" failed and exited with 1 during .

Your build has been stopped.
```

So, I did just revert that changes, and revert-revert this [into another, separate branch](https://github.com/username1565/text-encoding/tree/revert-3-revert-2-master).
When you'll fix this all, just open the another pull request,
and after merge this, I'll open the complete pull-request for @sinonjs

[One more branch](https://github.com/username1565/text-encoding/tree/feature/typescript) was been created from `revert-3-revert-2-master`-branch, and when you finish the work with this, you can open the pull request there too.

I just don't understand anything what that errors means. Hehheh.

**Comment by odahcam** [comment]
Thanks, haha. Actually I did not intend to propose all these changes at first, but just forgot I had openned this from master and kept commiting on it, that's a shame because unfortunatelly this messed up my changes and I don't think I'll be recreating them again. If you're interested you just gonna need 4 files from here:
- .travis.yml
- index.test.js 
- package.json 
- test-server.sh 
- (optional) test/README.md 
- (optional) yarn.lock

**Comment by username1565** [comment]
@odahcam, hm... I see all this files are already exists here: https://github.com/zxing-js/text-encoding
but... This page https://github.com/zxing-js/text-encoding/runs/657876220
still show the following error:
```
 The build errored.
```
As you can see in `Jobs and Stages`, this error is result of call `yarn : serve`:
```
error Command "test:serve" not found.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The command "yarn test:serve" failed and exited with 1 during .
```
I don't know how to fix it.

**Comment by odahcam** [comment]
This was a problem with the following commits, I do had it working when I proposed the PR. This is probably the closest working version I have to show: https://github.com/zxing-js/text-encoding/tree/7df02d8b721ecef580446d5d2e7d1d13b9149b3b 

This one version has a problem with the tests itself where it can't open the test URL in browser probably due to [this error](https://travis-ci.com/github/zxing-js/text-encoding/jobs/330799670#L291), so you could just change the URL port and try to make it work.

I'm sorry I messed this PR up. I already fixed it in my fork, but no more PRs intended as it's already too different. 

Cheers.

**Comment by username1565** [comment]
There is some problem here, [at this line](https://github.com/zxing-js/text-encoding/blob/a5f6db26a77fae5c53e4733a187fd44b96dd4161/.travis.yml#L13)

**Comment by username1565** [comment]
Seems like working with this code:
https://github.com/username1565/text-encoding/blob/1b68de1cb901f4d0a6b60b11f71e03d194e993f3/.travis.yml#L12-L16
but there is another error:
https://travis-ci.com/github/username1565/text-encoding/jobs/332151379
```
$ yarn run test:serve

yarn run v1.15.2

$ cd ./test && git submodule init && git submodule update --checkout && ../test-server.sh

/bin/sh: 1: ../test-server.sh: Permission denied

error Command failed with exit code 126.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The command "yarn run test:serve" exited with 126.
```
Maybe, need to run server not by this way:
https://github.com/username1565/text-encoding/blob/1b68de1cb901f4d0a6b60b11f71e03d194e993f3/test-server.sh#L2
but something, like this:
https://github.com/stopsopa/state-of-selenium/blob/64584d6302926c8cdaa757e2391e993743b3ac1e/Makefile#L15-L16
or this:
https://github.com/stopsopa/docker-puppeteer-html-scraper/blob/fb0e6fc5fadb99b9a4fbf896c93d086605f8803d/Makefile#L16-L17
or this:
https://github.com/lexand/micro-api-framework/blob/ace28b61792a66a7ff3c0f57d2d94e7bb1e908f5/tests/functional/start_test_server.sh

**Comment by username1565** [comment]
fix error about `access dinided`:
https://github.com/username1565/text-encoding/blob/ed8a4e362b6e84d22f9f93c5f73ab3b7e766bedb/.travis.yml#L11

**Comment by odahcam** [comment]
Yep, I already fixed all those errors in my fork, I just hoped you would grab the simpler version than this complex one I'm working on, but I'm glad you could find a solution for yourself. 🙂 

For fixing the access denied you gotta give the script [permissions trough git](https://stackoverflow.com/a/42187039/4367683):

```bash
git update-index --add --chmod=+x build.sh
git commit -m 'Make build.sh executable'
git push
```

Then it will run normally on Travis, you can see it working in my [`feature/typescript` branch](https://github.com/zxing-js/text-encoding/tree/feature/typescript).

Also, you can join me there as collaborator if you want, just let me know.

**Comment by username1565** [comment]
@odahcam, sorry I cann't collaborate with you, because I don't understand `TypeScript`, why this need, and what to do there.

Also, I see here https://travis-ci.com/github/zxing-js/text-encoding/branches
there is fail for both your branches.

I don't understand where need to put your previous code,
but I did change `.travis.yml`, and got progress with this:
https://travis-ci.com/github/username1565/text-encoding/jobs/332273791
but tests is failed... Cann't fix this, maybe you can.

Also, as you can see here: https://travis-ci.com/github/username1565/text-encoding/branches
master-branch is green. I'm not sure there is tests running, but `yarn run test:serve` not return any errors.
I just deleted my `revert-3-revert-2-master`-branch, and merge the changes to `master`-branch, after got success. And open the PR for you.

**Comment by odahcam** [comment]
> Also, I see here https://travis-ci.com/github/zxing-js/text-encoding/branches
there is fail for both your branches.

Yep, but the tests are fine, the source code that is wrong. That's because I'm doing TDD here, I first created the tests and make them run ok and know I'm going across the code fixing the errors the tests found for me.

> and dist-folder not found and not uploaded in your feature/typescript-branch.
I cann't fix this, maybe you can.

This folder is generated at compile-time, I do not code the contents in the, but TypeScript's compiler and other build scripts does that for me, that's why I point to that folder. So in my new TypeScript port, I always build the source code before running the tests, so dist is created before the tests run.

**Comment by username1565** [comment]
>Yep, but the tests are fine, the source code that is wrong. That's because I'm doing TDD here, I first created the tests and make them run ok and know I'm going across the code fixing the errors the tests found for me.

Hm... What means TDD?
As I understand, you run tests on the node, and travis running locally on the node for you?

>This folder is generated at compile-time, I do not code the contents in the, but TypeScript's compiler and other build scripts does that for me, that's why I point to that folder. So in my new TypeScript port, I always build the source code before running the tests, so dist is created before the tests run.

That error says `Cannot find module '../../dist/umd/encoding-indexes' from 'test/node/test-big5.spec.js'`
So, need to run some additional `TypeScript`-compilation, to create this `dist`-folder and allow access permission there, before compilation, or need to load already pre-compiled files in repositary?
Because this line already exists, but `dist`-folder is not created in repositary:
https://github.com/username1565/text-encoding/blob/29f767955bbfff95baa8be6f7ed3a639b64672b1/.travis.yml#L17
Maybe, this is created locally, when `travis`-build running, but

**Comment by odahcam** [comment]
> need to change umd to ./dist/umd, or change /dist/umd to /umd, but I'm not sure.

No need to change a thing. As you don't wanna use TypeScript you should be requiring files only from the lib/ folder.

> As I understand, you run tests on the node, and travis running locally on the node for you?

Yep.

> Hm... What means TDD?

[Test Driven Development](https://en.wikipedia.org/wiki/Test-driven_development).

**Comment by username1565** [comment]
>No need to change a thing. As you don't wanna use TypeScript you should be requiring files only from the lib/ folder.

As I said earlier, I did create my own [`feature/typescript`-branch](https://github.com/username1565/text-encoding/tree/feature/typescript) from your fork,
there is no `lib`-folder, and I just want to see green status here:
https://travis-ci.com/github/username1565/text-encoding/branches
for `feature/typescript`-branch, and I don't know how to fix this.

**Pull request merged**
